-- =========================================
-- MASTER UPDATE SCHEMA - TOTAL
-- Ejecutar esto para activar ficha técnica y variantes
-- =========================================

-- 1. Agregar columnas faltantes a productos
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS precio DECIMAL(10, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ficha_tecnica TEXT,
ADD COLUMN IF NOT EXISTS sku TEXT;

-- 2. Crear tabla de variantes si no existe
CREATE TABLE IF NOT EXISTS variantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL, 
    precio DECIMAL(10, 2) DEFAULT 0.00, 
    imagen_url TEXT, 
    stock INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Habilitar RLS
ALTER TABLE variantes ENABLE ROW LEVEL SECURITY;

-- 4. Políticas (Ignorar si ya existen)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Variantes Access') THEN
        CREATE POLICY "Public Variantes Access" ON variantes FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin All Access Variantes') THEN
        CREATE POLICY "Admin All Access Variantes" ON variantes FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;
