-- =========================================
-- ACTUALIZACIÓN DE SCHEMA - V2
-- Nuevas funcionalidades para Admin Panel
-- =========================================

-- 1. Agregar columnas a la tabla de productos
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS precio DECIMAL(10, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ficha_tecnica TEXT;

-- 2. Crear tabla de configuración del sitio
CREATE TABLE IF NOT EXISTS configuracion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logo_url TEXT,
    nombre_sitio TEXT DEFAULT 'GRUPO FERRENORTE RO&MY E.I.R.L',
    descripcion_sitio TEXT,
    contacto_whatsapp TEXT DEFAULT '51904068052',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Insertar configuración por defecto (solo si no existe)
INSERT INTO configuracion (logo_url, nombre_sitio, descripcion_sitio, contacto_whatsapp)
SELECT 'img/logo.jpeg', 'GRUPO FERRENORTE RO&MY E.I.R.L', 'Expertos en herramientas profesionales, EPP y equipamiento comercial.', '51904068052'
WHERE NOT EXISTS (SELECT 1 FROM configuracion);

-- 4. Habilitar RLS en configuracion
ALTER TABLE configuracion ENABLE ROW LEVEL SECURITY;

-- 5. Políticas de seguridad para configuracion
-- Cualquiera puede leer la configuración
CREATE POLICY "Public Config Access" ON configuracion
FOR SELECT USING (true);

-- Solo usuarios autenticados pueden modificarla
CREATE POLICY "Admin Update Config" ON configuracion
FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Admin Insert Config" ON configuracion
FOR INSERT WITH CHECK (auth.role() = 'authenticated');
