-- =========================================
-- ACTUALIZACIÓN DE SCHEMA - V3
-- Soporte para Variantes de Productos
-- =========================================

-- 1. Crear tabla de variantes
CREATE TABLE IF NOT EXISTS variantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL, -- Ej: "Color Negro", "Talla XL", "7 Puertas"
    precio DECIMAL(10, 2) DEFAULT 0.00, -- Precio específico para esta variante
    imagen_url TEXT, -- Imagen específica para esta variante
    stock INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Habilitar RLS en variantes
ALTER TABLE variantes ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de seguridad para variantes
-- Cualquiera puede leer las variantes
CREATE POLICY "Public Variantes Access" ON variantes
FOR SELECT USING (true);

-- Solo usuarios autenticados pueden modificarlas
CREATE POLICY "Admin All Access Variantes" ON variantes
FOR ALL USING (auth.role() = 'authenticated');

-- 4. Agregar columna de 'sku' o 'codigo' opcional a productos si no existe
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS sku TEXT;
